import './globals.css'
import { Comfortaa } from 'next/font/google'

const comfortaa = Comfortaa({
  weight: '400',
  subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>{children}</body>
    </html>
  )
}
