import './globals.css'
import { Phudu } from 'next/font/google'

const phudu = Phudu({
  weight: '500',
  subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={phudu.className}>{children}</body>
    </html>
  )
}
